name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Inspect Hostinger FTP Directory
        run: |
          npm install basic-ftp
          node -e "
          const ftp = require('basic-ftp');
          async function debug() {
            const client = new ftp.Client();
            client.ftp.verbose = true;
            try {
              await client.access({
                host: process.env.FTP_SERVER,
                user: process.env.FTP_USERNAME,
                password: process.env.FTP_PASSWORD,
                port: 21,
                secure: 'implicit' === false || true,
                secureOptions: { rejectUnauthorized: false }
              });
              console.log('=== CURRENT WORKING DIRECTORY ===');
              console.log(await client.pwd());
              console.log('=== LISTING FILES IN CURRENT DIRECTORY ===');
              console.log(await client.list());
            } catch(err) {
              console.error(err);
            }
            client.close();
          }
          debug();
          "
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
